version: '3'

services:
  postgres:
      image: postgres
      volumes:
        - keycloack-themes-postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:23.0.6
      command: start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_HOSTNAME: localhost
        KC_DB_SCHEMA: public
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pass;word1
      volumes:
        - ./themes/kdk:/opt/keycloak/themes/kdk      
        - ./themes/kapp:/opt/keycloak/themes/kapp
      ports:
        - 8080:8080
      depends_on:
        - postgres

volumes:
  keycloack-themes-postgres:
